#!/bin/bash

# Directory for archiving SSH keys
ARCHIVE_DIR="$HOME/.ssh/archive"

# Help function
sshenv_help() {
    echo "sshenv list"
    echo "======================"
    sshenv list
    echo "======================"
    echo
    echo "Usage: sshenv.sh [command] [arguments]"
    echo "Commands:"
    echo "  init [profile_name]     Initialize a new sshenv profile (using ~/.ssh/id_rsa, id_rsa.pub) and activate it"
    echo "  activate [profile_name] Activate SSH key-pair from the archive"
    echo "  list                    List all archived sshenv profiles"
    echo "  delete                  Delete the current sshenv profile (it does not delete ~/.ssh/id_rsa, id_rsa.pub)"
    echo "  switch                  Switch to the next sshenv profile"
    echo "  new [-f]                Generate a new SSH key-pair (requires -f to overwrite existing keys if not saved)"
}

# Function to initialize a new SSH key-pair profile and activate it
sshenv_init() {
    local profile_name=$1
    local target_dir="$ARCHIVE_DIR/$profile_name"

    # Create the archive directory if it doesn't exist
    mkdir -p "$target_dir"

    # Copy the current SSH key-pair to the archive
    cp ~/.ssh/id_rsa ~/.ssh/id_rsa.pub "$target_dir"
    # make immutable
    chmod a-w "$target_dir"
    chattr +i "$target_dir"

    # Create the activessh file in the archive
    echo "$profile_name" > "$target_dir/activessh"

    # Automatically activate the just-initiated profile
    sshenv_activate "$profile_name"
}

# Function to activate an SSH key-pair from the archive
sshenv_activate() {
    local profile_name=$1
    local source_dir="$ARCHIVE_DIR/$profile_name"

    if [[ -d "$source_dir" ]]; then
        # Copy the SSH key-pair from the archive to the default location
        cp "$source_dir/id_rsa" "$source_dir/id_rsa.pub" ~/.ssh

        # Update the activessh file in the home directory
        echo "$profile_name" > ~/.ssh/activessh
        # Display the list of profiles after activation
        sshenv_list
    else
        echo "Error: Archive $profile_name does not exist."
    fi
}

# Function to list all archived SSH key-pairs
sshenv_list() {
    if [[ -d "$ARCHIVE_DIR" ]]; then
        local current_ssh=$(cat ~/.ssh/activessh 2>/dev/null)
        for dir in "$ARCHIVE_DIR"/*/; do
            dir=${dir%*/}
            dir=${dir##*/}
            if [[ -f "$ARCHIVE_DIR/$dir/activessh" ]]; then
                if [[ "$dir" == "$current_ssh" ]]; then
                    echo "* $dir"
                else
                    echo "  $dir"
                fi
            fi
        done
    else
        echo "No archived SSH key-pairs found."
    fi
}

# Function to delete the current SSH key-pair
sshenv_delete() {
    local profile_name=$(cat ~/.ssh/activessh 2>/dev/null)
    dir_path=~/.ssh/archive/"$profile_name"
    chmod u+w "$dir_path"
    chattr -i "$dir_path"
    rm -rf "$dir_path"
    echo "Folder ~/.ssh/archive/$profile_name has been deleted."
}

# Function to switch to the next SSH key-pair in the list
sshenv_switch() {
    if [[ -d "$ARCHIVE_DIR" ]]; then
        local current_ssh=$(cat ~/.ssh/activessh 2>/dev/null)
        local ssh_keys=()
        for dir in "$ARCHIVE_DIR"/*/; do
            dir=${dir%*/}
            dir=${dir##*/}
            if [[ -f "$ARCHIVE_DIR/$dir/activessh" ]]; then
                ssh_keys+=("$dir")
            fi
        done
        if [[ ${#ssh_keys[@]} -eq 0 ]]; then
            echo "No archived SSH key-pairs found."
            return
        fi
        if [[ -z "$current_ssh" ]]; then
            sshenv_activate "${ssh_keys[0]}"
        else
            for i in "${!ssh_keys[@]}"; do
                if [[ "${ssh_keys[$i]}" == "$current_ssh" ]]; then
                    next_index=$(( (i + 1) % ${#ssh_keys[@]} ))
                    sshenv_activate "${ssh_keys[$next_index]}"
                    return
                fi
            done
        fi
    else
        echo "No archived SSH key-pairs found."
    fi
}

# Function to create a new SSH key-pair
sshenv_new() {
    local force_flag=$1

    # Check if the current id_rsa and id_rsa.pub are already archived
    local is_archived=false
    for dir in "$ARCHIVE_DIR"/*/; do
        if [[ -f "$dir/id_rsa" && -f "$dir/id_rsa.pub" ]]; then
            if cmp -s "$HOME/.ssh/id_rsa" "$dir/id_rsa" && cmp -s "$HOME/.ssh/id_rsa.pub" "$dir/id_rsa.pub"; then
                is_archived=true
                break
            fi
        fi
    done

    # If the keys are not archived, require the -f flag to overwrite
    if [[ "$is_archived" == false && "$force_flag" != "-f" ]]; then
        echo "Error: Current SSH keys are not archived. Use 'sshenv new -f' to force overwrite."
        return 1
    fi

    # Generate a new SSH key-pair
    ssh-keygen -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -P ""
    echo "<unknown profile>" > ~/.ssh/activessh
    echo "New SSH key-pair generated."
    if command -v pbcopy &> /dev/null; then
        cat $HOME/.ssh/id_rsa.pub | pbcopy
        echo "Public key copied to clipboard."
    else
        echo "Public key:"
        echo
        cat $HOME/.ssh/id_rsa.pub
    fi
}

sshenv() {
    # Main script logic
    case "$1" in
        init)
            if [[ -n "$2" ]]; then
                sshenv_init "$2"
            else
                echo "Error: Profile name is required."
                sshenv_help
            fi
            ;;
        activate)
            if [[ -n "$2" ]]; then
                sshenv_activate "$2"
            else
                sshenv_help
            fi
            ;;
        list)
            sshenv_list
            ;;
        delete)
            sshenv_delete
            ;;
        switch)
            sshenv_switch
            ;;
        new)
            sshenv_new "$2"
            ;;
        *)
            sshenv_help
            ;;
    esac
}

alias sdfv="sshenv switch"
alias sdf="sshenv activate"
